name       : python-semanticversion
version    : 2.8.5
release    : 4
source     :
    - https://github.com/rbarrois/python-semanticversion/archive/2.8.5.tar.gz : cd50a153e3bc5a8d53b2723601532b94b23e906d82d0b07cef421945f0e02107
homepage   : https://github.com/rbarrois/python-semanticversion
license    : BSD-2-Clause
component  : programming.python
summary    : Semantic version comparison for Python
description: |
    This small python library provides a few tools to handle SemVer in Python. It follows strictly the 2.0.0 version of the SemVer scheme.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
